export const theme = {
  bg: '#F7F8FA',
  surface: '#FFFFFF',
  surface2: '#EEF1F5',
  surfaceRaised: '#E3E8EF',
  surfaceElevated: '#FFFFFF',
  border: '#D7DEE7',
  borderHi: '#98A6B7',
  text: '#151A22',
  text2: '#525D6B',
  text3: '#8792A0',
  cyan: '#245F57',
  cyanDim: 'rgba(36,95,87,0.12)',
  accentContrast: '#FFFFFF',
  blue: '#2F66D0',
  blueDim: 'rgba(47,102,208,0.12)',
  green: '#128166',
  amber: '#A16605',
  rose: '#B34A60',
  sans: "'Geist Variable', 'Geist', 'Inter', system-ui, sans-serif",
  mono: "'JetBrains Mono Variable', 'JetBrains Mono', ui-monospace, monospace",
} as const;

export const focusCssVars = {
  '--bg': theme.bg,
  '--surface': theme.surface,
  '--surface-2': theme.surface2,
  '--surface-raised': theme.surfaceRaised,
  '--surface-elevated': theme.surfaceElevated,
  '--border': theme.border,
  '--border-hi': theme.borderHi,
  '--text': theme.text,
  '--text-2': theme.text2,
  '--text-3': theme.text3,
  '--accent': theme.blue,
  '--accent-dim': theme.blueDim,
  '--accent-contrast': theme.accentContrast,
  '--teal': theme.cyan,
  '--blue': theme.blue,
  '--green': theme.green,
  '--amber': theme.amber,
  '--rose': theme.rose,
  '--font-sans': theme.sans,
  '--font-mono': theme.mono,
} as const;
