export const theme = {
  bg: '#F5F7F4',
  surface: '#FFFFFF',
  surface2: '#EEF2EF',
  surfaceRaised: '#E5ECE7',
  surfaceElevated: '#FFFFFF',
  border: '#D7DED8',
  borderHi: '#9CAAA0',
  text: '#151C1A',
  text2: '#52615B',
  text3: '#89958F',
  cyan: '#245F57',
  cyanDim: 'rgba(36,95,87,0.12)',
  accentContrast: '#FFFFFF',
  blue: '#2F66D0',
  green: '#128166',
  amber: '#A16605',
  rose: '#B34A60',
  sans: "'Geist Variable', 'Geist', 'Inter', system-ui, sans-serif",
  mono: "'JetBrains Mono Variable', 'JetBrains Mono', ui-monospace, monospace",
} as const;

export const focusCssVars = {
  '--bg': theme.bg,
  '--surface': theme.surface,
  '--surface-2': theme.surface2,
  '--surface-raised': theme.surfaceRaised,
  '--surface-elevated': theme.surfaceElevated,
  '--border': theme.border,
  '--border-hi': theme.borderHi,
  '--text': theme.text,
  '--text-2': theme.text2,
  '--text-3': theme.text3,
  '--accent': theme.cyan,
  '--accent-dim': theme.cyanDim,
  '--accent-contrast': theme.accentContrast,
  '--blue': theme.blue,
  '--green': theme.green,
  '--amber': theme.amber,
  '--rose': theme.rose,
  '--font-sans': theme.sans,
  '--font-mono': theme.mono,
} as const;
