export const theme = {
  bg: '#F5F6F8',
  surface: '#FFFFFF',
  surface2: '#EEF1F5',
  surfaceRaised: '#E7EBF1',
  surfaceElevated: '#DDE4EC',
  border: '#D3DAE3',
  borderHi: '#AAB6C4',
  text: '#17202A',
  text2: '#53606D',
  text3: '#7E8A97',
  cyan: '#2F66D0',
  cyanDim: 'rgba(47,102,208,0.12)',
  accentContrast: '#FFFFFF',
  blue: '#4C5BD7',
  green: '#16865B',
  amber: '#A96700',
  rose: '#C34554',
  sans: "'Geist Variable', 'Geist', 'Inter', system-ui, sans-serif",
  mono: "'JetBrains Mono Variable', 'JetBrains Mono', ui-monospace, monospace",
} as const;

export const focusCssVars = {
  '--bg': theme.bg,
  '--surface': theme.surface,
  '--surface-2': theme.surface2,
  '--surface-raised': theme.surfaceRaised,
  '--surface-elevated': theme.surfaceElevated,
  '--border': theme.border,
  '--border-hi': theme.borderHi,
  '--text': theme.text,
  '--text-2': theme.text2,
  '--text-3': theme.text3,
  '--accent': theme.cyan,
  '--accent-dim': theme.cyanDim,
  '--accent-contrast': theme.accentContrast,
  '--blue': theme.blue,
  '--green': theme.green,
  '--amber': theme.amber,
  '--rose': theme.rose,
  '--font-sans': theme.sans,
  '--font-mono': theme.mono,
} as const;
